### ISSUE TITLE
Support for Mekanism gas

### ISSUE THREAD

**Issue by raoulvdberge** [refinedmods/refinedstorage2#134]
See RS 1 Addons request: https://github.com/refinedmods/refinedstorageaddons/issues/7

**Comment by BooBooFastCat1** [comment]
Will this add on be compatible with the radioactive chemicals from mekanism

**Comment by raoulvdberge** [comment]
The Mekanism integration will be provided as an addon.

This tracking issue will be closed now as the integration will be delivered as part of milestone 4 and the specific features have been planned on the project board: https://github.com/orgs/refinedmods/projects/6/views/9

(The features for the addon mod are tracked in a separate repo: https://github.com/refinedmods/refinedstorage2-mekanism-integration)
