### ISSUE TITLE
Colored cables

### ISSUE THREAD

**Issue by raoulvdberge** [refinedmods/refinedstorage2#172]
Separates networks.

**Comment by raoulvdberge** [comment]
white;white_dye
orange;orange_dye
magenta;magenta_dye
light_blue;light_blue_dye
yellow;yellow_dye
lime;lime_dye
pink;pink_dye
gray;gray_dye **DEFAULT**
light_gray;light_gray_dye
cyan;cyan_dye
purple;purple_dye
blue;blue_dye
brown;brown_dye
green;green_dye
red;red_dye
black;black_dye

**Comment by bulldog98** [comment]
How should the behavior be, should different colored cables connect to each other?

**Comment by raoulvdberge** [comment]
Different cable colors can't connect, for separation purposes.

**Comment by bulldog98** [comment]
> Different cable colors can't connect, for separation purposes.

Can they connect to any color of grid? I assume they can, since grid colors are only for customization

**Comment by raoulvdberge** [comment]
Yeah, they should be able to connect to any network block (besides different colored cables.)

Edit: I changed my mind on this. See #323

**Comment by bulldog98** [comment]
Should we first implement them with tint on the default cable to get the color, or do we have someone that is able to do art for that, since I'm not gonna lie I'm pretty bad at art.

**Comment by bulldog98** [comment]
Also do we want inworld recoloring? About the recipe do we have a recolor 8 at once or only a recolor 1 cable or both?

**Comment by raoulvdberge** [comment]
> Also do we want inworld recoloring?

Yes, like grids

> About the recipe do we have a recolor 8 at once or only a recolor 1 cable or both?

I'd allow recolor for 1 cable at a time, just like the recoloring recipes for grids etc.

> Should we first implement them with tint on the default cable to get the color, or do we have someone that is able to do art for that, since I'm not gonna lie I'm pretty bad at art.

I'll ask Cyanide if he can create some textures for us. Feel free to start on the impl with the default texture though.

**Comment by bulldog98** [comment]
Yeah I'll start implementing.

**Comment by bulldog98** [comment]
Do we want to keep the current color (black/dark_grey) as default color for cables?
