### ISSUE TITLE
can't close grid GUI after selecting search bar

### ISSUE THREAD

**Issue by AlexanderwithaA** [refinedmods/refinedstorage2#186]
### Describe the bug

You can't close the grid GUI through conventional means.
I've installed these mods for refined storage
![Screen Shot 2022-07-01 at 8 41 16 PM](https://user-images.githubusercontent.com/101488091/176985307-f5c174db-3110-4362-8e07-170ebf51440e.png)

### How can we reproduce this bug or crash?

If you select the search bar of the grid it seems to freeze for a brief second the first time you do it, but it keeps pressing the escape key from closing the GUI. However, if you have REI synchronization set to two way, you can type in the REI search bar and still close the GUI.

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge or Fabric version is this happening on?

fabricloader 0.14.8

### What Refined Storage version is this happening on?

milestone 1.4

**Comment by raoulvdberge** [comment]
It seems like it's no longer an issue on mc 1.19, this fix won't be backported to 1.18.
