### ISSUE TITLE
Liquid without in bucket item

### ISSUE THREAD

**Issue by szucconi** [refinedmods/refinedstorage2#190]
### Describe the bug

When you try to extract a liquid like honey from a fluid grid, since honey has no bucket item, the honey and a bucket disappear.  If we could instead fill bottles with honey or other liquid when the bucket item doesn't exist.  Or at least behave like no buckets exist and do nothing.  

### How can we reproduce this bug or crash?

I extracted honey from a centrifugal separator from the Thermal Mod and put it straight into a fluid interface.  Once the honey is in, I cant get it out.  Im not sure how to extract it via a fluid interface or exporter since I cant fill in the square for fluids.  I tried to fill a fluid encapsulater with a small amount of honey and let an external storage component move  the rest of the honey in, and it wouldnt.  I tried to use the disk manipulator to create a disk with only honey on it by adding all other fluids I had at the time to the black list.  This also fails.  But the disappearing is problematic,

### What Minecraft version is this happening on?

Minecraft 1.18.2

### What Forge or Fabric version is this happening on?

Forge

### What Refined Storage version is this happening on?

0.8.2

**Comment by raoulvdberge** [comment]
Is this about RS 2?
