### ISSUE TITLE
failed to start up 

### ISSUE THREAD

**Issue by micrwvae** [refinedmods/refinedstorage2#212]
### Describe the bug

when installing the v2.0.0 fabric jar to a client the game fails to start up
i installed the same jar on my server and it worked just fine

tried it with only refined storage and then with fabric api on 1.19 as well, and later on 19.1 with the same mods

### How can we reproduce this bug or crash?

1.download the jar from the release tab
2.add it to your mods folder alongside fabric api  for your current version
3.lauch the game

### What Minecraft version is this happening on?

Minecraft 1.19.1

### What Forge or Fabric version is this happening on?

0.14.9

### What Refined Storage version is this happening on?

refinedstorage2-platform-fabric-2.0.0-milestone.2.2.jar

### Relevant log output

```shell
https://mclo.gs/NIkUixE

full crash log
```

**Comment by micrwvae** [comment]
opened the jar and looked at the dependencies 
even after installing cloth config it didnt start up

tried it with with version 2.0 on 19 as well as 19.1 which worked fine
also with 2.1 on version 1.19 (https://mclo.gs/gqlBzxq) and 1.19.1 (https://mclo.gs/qRTsNMh)

**Comment by lzrdblzzrd** [comment]
I also get a crash related to net.minecraft.class_1088, but I don't have the Cloth Config installed. Only pure Minecraft with installed Fabric API and Refined Storage 2 (2.0.0-milestone.2.2).

I still can't figure out what exactly causes a crash, even on pure Minecraft without unnecessary mods installed.

https://mclo.gs/RoJY4Ru#L209

**Comment by raoulvdberge** [comment]
Thanks for the report. Has been fixed in v2.0.0-milestone.2.3.
