### ISSUE TITLE
The Disk Drive block is always turned in one direction

### ISSUE THREAD

**Issue by lzrdblzzrd** [refinedmods/refinedstorage2#215]
### Describe the bug

[A short video describing the whole bug](https://www.youtube.com/watch?v=6VsgXIiZ3Wo)

### How can we reproduce this bug or crash?

1. Place the Disk Drive block
2. Insert any disk into it

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge or Fabric version is this happening on?

0.14.9

### What Refined Storage version is this happening on?

v2.0.0-milestone.2.3

**Comment by raoulvdberge** [comment]
Which mods are installed?

**Comment by lzrdblzzrd** [comment]
![image](https://user-images.githubusercontent.com/32615368/186998654-f24db5de-770c-435b-b55e-124aa490ec47.png)
I think that this bug is caused only by the Sodium mod, since the rest, as far as I know, do not affect the rendering.

**Comment by raoulvdberge** [comment]
Try disabling sodium/lithium and let me know what happens.

**Comment by lzrdblzzrd** [comment]
I checked. Sodium causes this bug, Lithium has no effect.

**Comment by micrwvae** [comment]
u might be able to fix it if u add indium
https://modrinth.com/mod/indium

**Comment by lzrdblzzrd** [comment]
> u might be able to fix it if u add indium https://modrinth.com/mod/indium

I think this should be fixed at the Sodium level. As a temporary fix, i can install Indium, but i don't want it to be a mandatory dependency when playing with Sodium.

**Comment by raoulvdberge** [comment]
So did Indium work?

**Comment by micrwvae** [comment]
since it just is a visual bug and u r not required to play with sodium i dont think this small issue has high priority for them

**Comment by raoulvdberge** [comment]
Apparently Indium is important to gain Fabric Rendering API Support for Sodium.

I've added "NoIndium" mod packaged with RS2 to give warnings if you launch with Sodium but without Indium:

![image](https://user-images.githubusercontent.com/10358424/187030562-0438b4ba-94da-4037-bdce-dfa09e0fb712.png)
