### ISSUE TITLE
Power Problems

### ISSUE THREAD

**Issue by bloodscon** [refinedmods/refinedstorage2#221]
### Describe your enhancement

In the past one of the limits for RS is power might be an idea to have a way to upgrade the power storage of the mod also maybe a tool to check/see network so if you have the tool held the cable will be highlighted but if you have an unpowered cable in the world it would highlight say red to show disconnected.  Was also going to ask about subnetting but noticed already on projects board 👍

**Comment by raoulvdberge** [comment]
Rs2 supports multiple controllers
