### ISSUE TITLE
Use Gradle version catalogs

### ISSUE THREAD

**Issue by raoulvdberge** [refinedmods/refinedstorage2#234]

**Comment by bulldog98** [comment]
Which one would you prefer settings.gradle.kts or gradle/libs.versions.toml?

**Comment by raoulvdberge** [comment]
@bulldog98 Sorry, I forgot about your comment! I'd prefer it to be regular Groovy in `settings.gradle`. We could then get (mostly) rid of `gradle.properties` (except for the `org.gradle.jvmargs` part).

**Comment by bulldog98** [comment]
@raoulvdberge I had a look at the issue, and the syntax for the catalog change between gradle 7.3 and 7.6, should we update gradle first?

**Comment by raoulvdberge** [comment]
@bulldog98 That's fine - first check if it's possible with Forge/Fabric though to update.

**Comment by bulldog98** [comment]
7.6 does not work, but 7.5 does, and it already uses the new syntax
