### ISSUE TITLE
Remove log4j usage

### ISSUE THREAD

**Issue by raoulvdberge** [refinedmods/refinedstorage2#251]
Since Minecraft 1.18.2 Minecraft ships Slf4j.

Actions needed:

- We can drop our Log4j dependencies in the `*-api` modules, and depend on Slf4j instead (best to pick same version number as Minecraft)
- We need to start using Slf4j in our `*-api` modules.
  - The tests need a Slf4j implementation like Log4j2, so we still get logging there. 
- We need to start using Slf4j in our Minecraft platform modules.

**Comment by bulldog98** [comment]
Is it ok for me to take this?

**Comment by raoulvdberge** [comment]
Yes, go ahead :-)

**Comment by bulldog98** [comment]
I had a look at the tests. They use log4j currently, but do not configure it, so there is no output from logging. Do we want to keep that behavior, or do we want logging in tests? (Then I suggest using slf4j-simple, since it does not require any configuration)

**Comment by raoulvdberge** [comment]
Yes, slf4j-simple is a good idea! The less configuration, the better.

**Comment by raoulvdberge** [comment]
Oh, another idea: it might be a good idea to add log4j to the disallowed imports in our Checkstyle config as Log4j is still on the classpath on mc-side.
