### ISSUE TITLE
Add branch name linting

### ISSUE THREAD

**Issue by raoulvdberge** [refinedmods/refinedstorage2#265]
With #264 we'll start using merge commits instead of rebase pushing when merging a PR.

That means that branch names will go in the history of `develop`

That also means that we probably need better branch name linting.

I propose

`fix/GH-1234/alphanumeric-description-of-changes-no-uppercase`
`feature/GH-1234/alphanumeric-description-of-changes-no-uppercase`

**Comment by bulldog98** [comment]
What about refactors, just `refactor/GH-1234/alphanumeric-description-of-changes-no-uppercase`?

**Comment by bulldog98** [comment]
Also we should not forget to document that

**Comment by raoulvdberge** [comment]
Yes needs to be documented in contributing

We can probably allow the same category names as used in commitlint?

**Comment by bulldog98** [comment]
I'm personally more in favor of branchnames like `fix/1234-alphanumeric-description-of-changes-no-uppercase`

**Comment by raoulvdberge** [comment]
I like the GH prefix to clarify it's a GitHub issue (if we'd ever migrate to something else).

Also, GH makes a link out of it:
![image](https://user-images.githubusercontent.com/10358424/211552231-71ef71e1-acd0-46a2-83cd-609e078e8518.png)

**Comment by raoulvdberge** [comment]
We need to differantiate between release/hotfix branches and regular branches.

Release hotfix format should be `release/SEMVER HERE` or `hotfix/SEMVER HERE`.
