### ISSUE TITLE
Recoloring of Grid via crafting not complete

### ISSUE THREAD

**Issue by bulldog98** [refinedmods/refinedstorage2#266]
### Describe the bug

If you want to recolor a red grid to the default color, you have to place it and apply the color by hand. But you should be able to just craft it with the red dye.

### How can we reproduce this bug or crash?

try to recolor a red grid with light_blue dye in a shapeless craft.

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge or Fabric version is this happening on?

both

### What Refined Storage version is this happening on?

current dev

**Comment by bulldog98** [comment]
@raoulvdberge could you assign me

**Comment by raoulvdberge** [comment]
Done, thanks!
