### ISSUE TITLE
Add collapsable entries support for REI

### ISSUE THREAD

**Issue by bulldog98** [refinedmods/refinedstorage2#270]
### Describe your enhancement

Rei has this newish feature of collapsable entries (https://github.com/shedaniel/RoughlyEnoughItems/blob/9.x-1.19/api/src/main/java/me/shedaniel/rei/api/client/registry/entry/CollapsibleEntryRegistry.java) and for Jei there is also a suggestion for it (https://github.com/mezz/JustEnoughItems/issues/2918). We should implement that in our plugins, to group all the different colored items to one.

**Comment by raoulvdberge** [comment]
Implement this after #320
