### ISSUE TITLE
Disk drive has extra slot

### ISSUE THREAD

**Issue by tonyaellie** [refinedmods/refinedstorage2#327]
### Describe the bug

there is an extra slot at the bottom of the disk drive
![image](https://user-images.githubusercontent.com/46281725/219117291-fd57dfb9-815c-4695-a75a-653f09030c21.png)
![image](https://user-images.githubusercontent.com/46281725/219117338-6b54febd-6b72-4694-987c-99158597903b.png)

### How can we reproduce this bug or crash?

1. Launch fabric 1.19.3 with fabric api and re2 installed
2. place a disk drive
3. observe extra slot 

### What Minecraft version is this happening on?

Minecraft 1.19.3

### What Forge or Fabric version is this happening on?

fabric 0.14.14

### What Refined Storage version is this happening on?

re2 2.0.0-milestone.2.7

**Comment by bulldog98** [comment]
Happens in forge too.
