### ISSUE TITLE
GUI exclusion zones for JEI/REI

### ISSUE THREAD

**Issue by raoulvdberge** [refinedmods/refinedstorage2#344]
### Describe your enhancement

The JEI/REI widgets are colliding/conflicting with the side buttons in the GUI. Tell the JEI/REI API that we have extra widgets rendered outside the GUI bounds!

**Comment by bulldog98** [comment]
Are you ok, with me taking this one?

**Comment by raoulvdberge** [comment]
Go ahead!

**Comment by raoulvdberge** [comment]
@bulldog98  are you still interested in working on this? :D

**Comment by bulldog98** [comment]
@raoulvdberge I looked at it and was not really able to find out how to do it.
