### ISSUE TITLE
Refined Storage oddities with Mystic Agriculture

### ISSUE THREAD

**Issue by Simon-Bitdiddle** [refinedmods/refinedstorage2#37]
Version and correlating: Using mod version 1.9.15 with Refined Storage Addons 0.7.3 under FTB Oceanblock ver 1.7.0

Issue(s):
1) Reoccurrence of a previous autocrafting issue with mystical agriculture supremium #788

2) Replacing Master Infusion Crystal with with degradable Infusion Crystal if 'Exact' is not checked in pattern.

Explanation:
1) Issue with requiring multiples of a functionally infinite item as part of a recipe unable to be worked around as there is no method to force processing.

2) Using a standard Prudentium recipe with a Master Infusion Crystal and no degradable Infusion crystal.

Using the 'Exact' option in the pattern works as expected with Master Infusion Crystal returning into inventory system.

Unchecking processes as expected besides the Master Infusion Crystal converting to a standard Infusion Crystal with 999 uses remaining.

**Comment by raoulvdberge** [comment]
Wrong repo
