### ISSUE TITLE
ignoring nbt when crafting

### ISSUE THREAD

**Issue by lucasser** [refinedmods/refinedstorage2#371]
### Describe your enhancement

When clicking in recipes form jei that use armour, or nbt related items, instead of not recognizing that the item exists in the grid, it is dragged into the grid regardless of nbt. Example: ad astra mod, crafting plates requires a hammer, and an ingot. Right now, if there is a hammer with partial durability in the grid, rs will not recognize it, and will show missing ingredients in jei.

**Comment by raoulvdberge** [comment]
Which RS version are you on?

**Comment by lucasser** [comment]
Refined storage 1.11.6
