### ISSUE TITLE
Pattern TANKS frames while looking at it, or having it in inventory

### ISSUE THREAD

**Issue by lcpichette** [refinedmods/refinedstorage2#379]
### Describe the bug

I made a pattern with a platinum hammer and a an iron ore to make iron dust.

I also have a platinum hammer pattern, and other patterns.

Suddenly, my game TANKED in frames upon making the pattern. I tossed the pattern using Q, and looked away from it instinctively. My frames returned to normal.

I cannot trash the item (I don't know what mod provides it, but it's a trash icon/slot at the bottom right of inventory), so I had to put it in a chest with a sign saying "DO NOT OPEN", I could probably delete it with lava, but for now that seems to work. 

https://github.com/refinedmods/refinedstorage2/assets/54318714/0c110f93-d0e5-4128-886a-5e9c73c33a9d

It's not a big deal once you know what the issue is, but I think that some people might not be able to figure out what the issue is here.

### How can we reproduce this bug or crash?

1. Create necessary RS2 setup to create patterns
2. Create a hammer from All The Ores (I was using platinum, I'm not sure if this is an issue with the other hammers)
3. Use the hammer and an ore with a pattern grid to create a pattern that uses the hammer (non-exact, non-processing) to create dust. 
4. You should now have the pattern of-subject which tanks frames

### What Minecraft version is this happening on?

Minecraft 1.19.2

### What Forge or Fabric version is this happening on?

CurseForge, ATM8 v1.0.19b

### What Refined Storage version is this happening on?

1.11.6

**Comment by lcpichette** [comment]
As the issue submitter, it would be great to hear why this was closed. 

I took the time to create reproduceable steps, create a video better showing the issue, and deliver the report.

I feel that, as the ticket closer, taking the time to explain why an issue is being closed is warranted. "closed this as not planned" isn't a great explanation either, IMO.

**Comment by raoulvdberge** [comment]
You posted this on the wrong repository

**Comment by lcpichette** [comment]
> You posted this on the wrong repository

What repository should this have been posted to? Thank you for the response.

**Comment by jonatjano** [comment]
You're supposed to post it on the refined storage repo, since you're currently using refined storage and not refined storage 2
https://github.com/refinedmods/refinedstorage

**Comment by lcpichette** [comment]
Thank you @jonatjano! I've posted it to the [correct location](https://github.com/refinedmods/refinedstorage/issues/3512) now. I appreciate you taking the time to help resolve this issue by informing me of the right place to submit it. I hope you have a nice day!
