### ISSUE TITLE
Disks filling up have wrong behavior

### ISSUE THREAD

**Issue by denisloch** [refinedmods/refinedstorage2#423]
### Describe the bug

Normally, with the disk drive and item/fluid storage disks inside of it, when adding items to the system, the first disk should fill up first, then the next one should follow and this behavior should repeat until the entire storage is full.
Unfortunately, that is not the behavior. What's happening is that all storage disks are filling up at the same time. Then, when you remove the storage disks and reinsert them into the disk drive, the items are duplicated. The same behavior happens to fluid storage disks (when for example filling them up by utilizing a destructor).

### How can we reproduce this bug or crash?

See short [video](https://imgur.com/a/MHtAZnL) detailing the process of encountering the bug.

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge or Fabric version is this happening on?

using quilt-loader-0.19-1.20.1 (fabric compatible)

### What Refined Storage version is this happening on?

v2.0.0-milestone.2.14 (latest)

**Comment by raoulvdberge** [comment]
Yes, because you have duplicated the disks with middle click. This duplicates the storage ID stored on the disk, causing you to insert the same storage N times, which will get you the behavior you demonstrated.

**Comment by denisloch** [comment]
oh, that makes sense - please excuse the mistake on my part

**Comment by raoulvdberge** [comment]
No worries, thanks for testing!
