### ISSUE TITLE
items refuse to stack in the system

### ISSUE THREAD

**Issue by broz21** [refinedmods/refinedstorage2#457]
### Describe the bug

It only started to happen recently, but items put manually in the storage refuse to stack. It seems like it also happens in my inventory, so i do not know if it is a refined storage specific bug or something else.

### How can we reproduce this bug or crash?

1-make the game laggy
2-put manually two seperated stacks of any items
3-i guess try multiple times

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge or Fabric version is this happening on?

forge-47.2.1

### What Refined Storage version is this happening on?

1.12.4

**Comment by raoulvdberge** [comment]
You created this issue in the wrong repository

**Comment by broz21** [comment]
was i supposed to open it in the community support repository?

**Comment by jonatjano** [comment]
Since your issue is happening on a version starting with a 1, then the right repository is the one for [refined storage 1](https://github.com/refinedmods/refinedstorage)
