### ISSUE TITLE
Multi input autocrafting 

### ISSUE THREAD

**Issue by lucasser** [refinedmods/refinedstorage2#458]
### Describe your enhancement

In addition to rs1 crafters, add some block (a different crafter, or add-ons to the existing one) that will allow for large recipes hopefully over 9 ingredients, that have multiple inputs, the simplest example being created crafters or Mystical agriculture seed crafting. So there would be a pattern that has the resources, and some exporters or something that put those resources in the correct places.

**Comment by raoulvdberge** [comment]
How is this different from processing patterns?
