### ISSUE TITLE
Chinese localization

### ISSUE THREAD

**Issue by Jiangsubei** [refinedmods/refinedstorage2#469]
### Describe your enhancement

Hello developers, I have localized the content of this mod on my end. Although the translation may not be entirely accurate yet, I hope to include it in the next update. Thank you very much.
[zh_cn.json](https://github.com/refinedmods/refinedstorage2/files/14029318/zh_cn.json)

**Comment by raoulvdberge** [comment]
Hello, RS 2 is still under active development so the translations still change a lot, so usually I wouldn't accept any translation changes at this point. 

However I understand that for the Chinese community a translation is important so I'll apply this, thanks!

**Comment by Jiangsubei** [comment]
I understand and respect your decision. Sincere thanks for your response here. I hope your development progresses smoothly!

**Comment by raoulvdberge** [comment]
@Jiangsubei Thank you, the translation has been applied in v2.0.0-milestone.3.3

**Comment by raoulvdberge** [comment]
Hi @Jiangsubei , you can now also contribute on Crowdin: https://crowdin.com/project/refined-storage-2
