### ISSUE TITLE
Easier fluid manipulation

### ISSUE THREAD

**Issue by BlueHero233** [refinedmods/refinedstorage2#481]
### Describe your enhancement

1: drag and dropping fluids from jei to import/export/interface filters

or

2: allowing modded tanks (pneumaticcraft, mekanism, evilcraft) to act as a bucket

I have a quarter bucket of sulfuric acid from gtceu on my fluid grid just but i cant take it out because its less than 1000mb, cant set a exporter because you cant drag the fluid from jei like you would with an item and you cant use an tank from any other mod to pull said liquid from the grid so i can set the exporter

“Well just make more sulfuric acid” i know its silly but i think i would be disappointed if i got my .864 buckets of molten yttrium barium cuprate alloy on my fluid grid and i cant take it out

**Comment by raoulvdberge** [comment]
It should be possible to drag/drop fluids from JEI in the filter slots? Which version of RS 2 are you using?

**Comment by BlueHero233** [comment]
1.12.4 for minecraft 1.20.1 
If it matters the All The Mods 9 modpack version 0.2.40
Is the version up on curse *not* refined storage 2?

**Comment by raoulvdberge** [comment]
No. The version of Curse is Refined Storage 1.

**Comment by BlueHero233** [comment]
Which file of the releases should i install then? The refinedstorage2-platform-forge-2.0.0-milestone.3.2.jar 
Also when do you plan on updating the curse page

**Comment by jonatjano** [comment]
@BlueHero233 the file you named is the correct one, but be aware that RS2 doesn' have autocraft
the curse page will be updated once RS2 has feature parity with RS1

**Comment by BlueHero233** [comment]
Sweet, i might even play test the latest release
