### ISSUE TITLE
Incorrect menu title for wireless grids

### ISSUE THREAD

**Issue by BooBooFastCat1** [refinedmods/refinedstorage2#502]
### Describe the bug

![image](https://github.com/refinedmods/refinedstorage2/assets/121510765/6052946c-17af-4dc9-82eb-6e7f7d6e0536)
the text at the top of the wireless grid is incorrect

also it is acutally happening on 1.20.4 but i cant select it below

### How can we reproduce this bug or crash?

1. get a wireless grid
2. link it to a controller
3. open the wireless grid

### What Minecraft version is this happening on?

Minecraft 1.20.1

### What Forge or Fabric version is this happening on?

Neoforge

### What Refined Storage version is this happening on?

refined storage 2 v2.0.0 milestone 3.4

**Comment by raoulvdberge** [comment]
Thanks.
