### ISSUE TITLE
The drawing order of tooltips is incorrect

### ISSUE THREAD

**Issue by BloCamLimb** [refinedmods/refinedstorage2#543]
### Describe the bug

Tooltips have transparency and its Z value is 400, if the tooltip is drawn first, then all the elements that are drawn later will be discarded by depth test. So you cannot draw tooltips immediately before all elements with Z<400 are drawn.
https://github.com/refinedmods/refinedstorage2/blob/4e73ddbd75e6391ed382dbd33b9f05b4da2a46fb/refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/support/widget/AbstractSideButtonWidget.java#L51-L74

`Screen#setTooltipForNextRenderPass` is the right way to go. Please refer to this issue for a detailed explanation https://github.com/BloCamLimb/ModernUI/issues/216

### How can we reproduce this bug or crash?

The issue is just there, `Platform.INSTANCE.renderTooltip(graphics, buildTooltip(), mouseX, mouseY);` should not be called at that time.
https://github.com/refinedmods/refinedstorage2/blob/4e73ddbd75e6391ed382dbd33b9f05b4da2a46fb/refinedstorage2-platform-common/src/main/java/com/refinedmods/refinedstorage2/platform/common/support/widget/AbstractSideButtonWidget.java#L51-L74

### What Minecraft version is this happening on?

Minecraft 1.20.4

### What NeoForge or Fabric version is this happening on?

The latest version at this moment

### What Refined Storage version is this happening on?

The latest version at this moment

**Comment by raoulvdberge** [comment]
Thanks for reporting back, this will be fixed for mc 1.20.4.
