### ISSUE TITLE
Cursor has to be empty to take out fluids in form of buckets

### ISSUE THREAD

**Issue by starforcraft** [refinedmods/refinedstorage2#617]
### Describe the bug

It's not possible to take out fluids while dragging an empty bucket. The cursor must be empty for it to work.

https://github.com/user-attachments/assets/b68e5ac5-777e-43b2-ad3d-d172e25ff08c

### How can we reproduce this bug or crash?

1. Put water into the grid
2. Try to pick it up while dragging an empty bucket

### What Minecraft version is this happening on?

Minecraft 1.21

### What NeoForge or Fabric version is this happening on?

21.0.61-beta

### What Refined Storage version is this happening on?

v2.0.0-milestone.4.4

**Comment by BooBooFastCat1** [comment]
will this work with the mekanism integration and allow you to extract gasses with chemical tanks/pippets

**Comment by starforcraft** [comment]
Yes
