### ISSUE TITLE
Processor Binding is not craftable (slimeball is missing)

### ISSUE THREAD

**Issue by starforcraft** [refinedmods/refinedstorage2#625]
### Describe the bug

This only happens on fabric.
![grafik](https://github.com/user-attachments/assets/8bcfec11-f8c2-4d7b-a731-9604bde4bd16)

Caused by:
```
    "L": {
      "tag": "c:slimeballs"
    }
```
Because there is no convention tag for slimeballs on fabric (Source: https://github.com/FabricMC/fabric/tree/1.21/fabric-convention-tags-v2/src/generated/resources/data/c/tags/item)

### How can we reproduce this bug or crash?

1. Try to craft a processor binding or look at the recipe in jei/rei/emi
2. Slimeball in the middle is missing

### What Minecraft version is this happening on?

Minecraft 1.21

### What NeoForge or Fabric version is this happening on?

Fabric 0.100.4+1.21

### What Refined Storage version is this happening on?

v2.0.0-milestone.4.4

**Comment by raoulvdberge** [comment]
https://github.com/FabricMC/fabric/issues/3946

**Comment by raoulvdberge** [comment]
>can you make a fabric api issue report please
> not all tags are in sync since unify was focusing on most use cases. I do like to see more of the nicher ones get synced overtime now

**Comment by raoulvdberge** [comment]
Fixed by #654 

Duplicate issue was #644
