### ISSUE TITLE
Hope to merge my translation 希望对合并我的翻译

### ISSUE THREAD

**Issue by wangbohan090709081** [refinedmods/refinedstorage2#673]
Dear developer raoulvdberge Raoul Hello
I am very interested in this Refined Storage 2 Mod
Because the well-known Chinese mod website Mcmod.cn records that Refined Storage has fabric support, the URL is https://www.mcmod.cn/class/691.html, so I have been looking for the Fabric version of this Refined Storage, but I didn’t find it on curseforage or modirnth. After a lot of searching, I found the Refined Storage 2 version. I just hope that my friends and I can play the game in Chinese, and at the same time help players who want to play
This mod has been translated into Chinese a lot, so I have completed it. Now, there is only simplified Chinese that has completed 100% translation. I hope you can review and merge it into the new version as soon as possible
I translated it on crowdin
In this translation, I appropriately used the power of AI. At the same time, I reviewed the translated parts to make them roughly the same style. There may still be some translation errors, welcome to correct them
The game I play is 1.20.1 fabric  Although my translation is not compatible with this version, and this version has been translated, I am still happy to contribute to the new version.
The real reason is that Applied Energy (AE2) is too difficult to use.
In addition, I have a few questions.
1. Why do you want to release a new version, Refined Storage 2, instead of using the old version?
2. Why don't you continue to update curseforage and modirnth?
I wish you good health and good luck.
If you can read simplified Chinese, please try to read the text below. English uses Google Translate.

尊敬的开发者 raoulvdberge Raoul 你好
我对这个Refined Storage 2 Mod 模组很感兴趣
因为中国知名模组网站Mcmod.cn记载Refined Storage 有fabric支持，网址https://www.mcmod.cn/class/691.html所以我一直在寻找这个Refined Storage 的Fabric版本，但我不论在curseforage或者modirnth上面都没有找到，经过我一番寻找，我发现了Refined Storage 2这个版本，我只是希望我和朋友可以使用中文进行游戏，同时帮助希望有玩的玩家
这个模组已经为中文翻译了不少，所以我进行了补全，现在，有且仅有简体中文完成了100%的翻译，希望您可以尽快审查并合并到新版本
我在crowdin上面进行翻译的
在这个翻译中，我适当的借助了AI的力量，同时，我翻阅了已经翻译的部分，使其风格大致相同，可能仍然有部分翻译错误，欢迎指正
我玩的游戏是1.20.1 fabric 尽管我的翻译和这个版本不兼容，同事，这个版本已经完成了翻译，但我仍然为可以为新版本贡献一份力量而高兴
其实真正的原因是应用能源（AE2）过于难用
另外，我有几个问题
1.为何要独立出一个新版本Refined Storage 2，不沿用旧版本
2.为何不在curseforage和modirnth继续更新
祝您身体健康，完事如意
如果您有阅读简体中文的能力，请尽量阅读下面文字，英文使用的是Google翻译

**Comment by wangbohan090709081** [comment]
pic
![Screenshot_2024-08-20-01-17-34-640_com.microsoft.emmx-edit.jpg](https://github.com/user-attachments/assets/2981949b-b20d-4d1b-955f-36549636e339)

![Screenshot_2024-08-20-01-50-23-124_com.microsoft.emmx-edit.jpg](https://github.com/user-attachments/assets/da292a15-b0a6-4c96-b67c-7d104274b4b3)

![Screenshot_2024-08-20-01-46-16-788_com.microsoft.emmx.jpg](https://github.com/user-attachments/assets/9076bd86-7c8c-45aa-a5f3-6d2753416638)


https://github.com/user-attachments/files/16663748/zh_CN.json

**Comment by raoulvdberge** [comment]
Hello, thanks for the translation. This will be applied to the next version of milestone 4, for Minecraft 1.21.

RS 2 for Minecraft 1.20.1 is unmaintained as it's an old version and Refined Storage 2 is a work in progress.

> Why do you want to release a new version, Refined Storage 2, instead of using the old version?

https://github.com/refinedmods/refinedstorage2/wiki/Why-Refined-Storage-2%3F

> Why don't you continue to update curseforage and modirnth?

https://github.com/refinedmods/refinedstorage2/wiki/FAQ#when-will-refined-storage-2-be-released-on-curseforge-or-modrinth

**Comment by wangbohan090709081** [comment]
I can't find a 1.20.1 fabric version!
and i need to use fabric mods

**Comment by wangbohan090709081** [comment]
and thanks for answer me
