### ISSUE TITLE
Portable Storage not charging properly as item

### ISSUE THREAD

**Issue by jshipley** [refinedmods/refinedstorage2#696]
### Describe the bug

This is all in relation to using the Portable Grid as an item, not placing it as a block.

When placed into an item charger (Tech Reborn's Charge-O-Mat or Oritech's Portable Energy Storage), the charging block continuously loses energy while the Portable Grid's power level doesn't change.

Similarly, having a Portable Grid in your inventory while wearing Tech Reborn's Lithium Battpack or Oritech's Exo Chestplate, the energy level of the battery will continuously drain and the Portable Grid's energy level will not change.

I did notice that the Portable Grid does seem to be getting appropriately charged with an Inventory Coal Engine from Energized Power.

### How can we reproduce this bug or crash?

* Install RS2 with Tech Reborn or Oritech
* Try to charge a Portable Grid with a Battpack, Exo Chestplate, Charge-O-Mat, or Portable Energy Storage
* Watch the energy storage of the charger drain continuously while the Portable Grid's energy storage doesn't change

### What Minecraft version is this happening on?

Minecraft 1.21.1

### What NeoForge or Fabric version is this happening on?

Fabric 0.15.0+1.21.1

### What Refined Storage version is this happening on?

2.0.0-minestone.4.7 and 0.0.0+e959881 (latest from actions)

### Relevant log output

```shell
There was nothing logged while this was occurring.
```

**Comment by raoulvdberge** [comment]
After some investigating, this appears to be a TechReborn issue.
See: https://github.com/TechReborn/TechReborn/issues/3302

I'll check Oritech now to see if it's a similar issue.

**Comment by raoulvdberge** [comment]
Also created an issue on Oritech's end:
https://github.com/Rearth/Oritech/issues/105

Appears to be the same problem.

**Comment by raoulvdberge** [comment]
I've reported it to the relevant mods. If more info comes up we can reopen this issue.

**Comment by raoulvdberge** [comment]
This will be fixed when I integrate https://github.com/refinedmods/refinedstorage2/pull/728
