### ISSUE TITLE
Craft Till get recipe feature support

### ISSUE THREAD

**Issue by edotenseilove** [refinedmods/refinedstorage2#722]
### Describe your enhancement

A special type of a processing recipe support that would be used for a chance based recipes where the output Is not guaranted I would imagine IT Beeing a special type of a pattern where the insertion delay could be set (timer after which the recipe Will be repeated if output of a recipe Is not recieved from the craft.)

**Comment by Nodrance** [comment]
The usual way I deal with that is to overestimate. Like if you have a 20% chance of getting what you want, make it an 8->1 recipe

**Comment by Nodrance** [comment]
Alternatively, make it passive using a detector and exporter

**Comment by jonatjano** [comment]
While this issue was closed as `won't fix`, I think you will be interested in the [planned redstone autocrafter variant](https://github.com/refinedmods/refinedstorage2/issues/686)
