### ISSUE TITLE
[ BUG ] Automatically add the task of synthesizing items without adding a synthesis formula

### ISSUE THREAD

**Issue by windy664** [refinedmods/refinedstorage2#731]
### Describe the bug

When these two items are used on the Internet, a synthesis sequence will be added until the synthesis list reaches the upper limit, and the corresponding items are put in for synthesis but no automatically synthesized items are found.

### How can we reproduce this bug or crash?

![2c638e0922e7ba36632aa224c6c11f2f](https://github.com/user-attachments/assets/611fb0c7-95b4-4afe-8de4-0a8de289bb08)
![e141511b254f65b6e678e69a4c7113a9](https://github.com/user-attachments/assets/d518d228-bd21-4ef6-b5f3-701e9a8ea0c9)
![6eeff9172e87fb36c2a9cdc23dc34ef3_720](https://github.com/user-attachments/assets/b9b986f3-3c6d-427a-9873-2d32acfa0218)

### What Minecraft version is this happening on?

Minecraft 1.21.1

### What NeoForge or Fabric version is this happening on?

21.1.64

### What Refined Storage version is this happening on?

refinedstorage-neoforge-2.0.0-milestone.4.10

**Comment by raoulvdberge** [comment]
It's not finished yet, this is fake/dummy data for testing. Please read the project description and goals on the FAQ.
