### ISSUE TITLE
"Remember search query" config setting does not take effect

### ISSUE THREAD

**Issue by Moj-FPS** [refinedmods/refinedstorage2#734]
### Describe the bug

The previous search term in the search bar of the crafting grid is always shown. The config value for "Remember search query" is set to "OFF" by default. Toggling it to "ON" and back to "OFF" had no effect.

### How can we reproduce this bug or crash?

1. Check crafting grid config for "Remember search query" 
2. Set to "OFF"
3. Type in search term in crafting grid
4. Exit crafting grid
5. Enter crafting grid
6. Search term is still displayed

### What Minecraft version is this happening on?

Minecraft 1.21.1

### What NeoForge or Fabric version is this happening on?

NeoForge 21.1.81

### What Refined Storage version is this happening on?

2.0.0-milestone.4.10

### Relevant log output

```shell
N/A
```

**Comment by raoulvdberge** [comment]
I cannot reproduce this. When I set it from "ON" to "OFF", the contents of the text field are always cleared when opening the grid.

**Comment by raoulvdberge** [comment]
I'll close this for now. Can you retry with your reproduction steps and report back if you can still reproduce it?

**Comment by Moj-FPS** [comment]
Sure! I'll do some testing in a bit here, it's definitely possible I missed
something.

**Comment by Moj-FPS** [comment]
I figured it out. I had it set to Two-Way JEI Synchronization, so since JEI was remembering the search query it was automatically in RS. Switched it back to one-way and it works just fine. 🤦‍♂️ My bad!

**Comment by raoulvdberge** [comment]
No worries, thanks for reporting anyways.
