### ISSUE TITLE
Cannot remove Silent Gear weapons/tools from grid

### ISSUE THREAD

**Issue by Moj-FPS** [refinedmods/refinedstorage2#735]
### Describe the bug

If you store a Silent Gear weapon or tool in the grid, you cannot remove them manually. I was able to retrieve them by crafting weapons/tools of the same construction and using an exporter filtered to each respective weapon/tool.

### How can we reproduce this bug or crash?

1. Store Silent Gear weapon or tool in grid
2. Shift-click to retrieve weapon or tool in grid with no result
3. Attempt to drag weapon or tool from grid with no result

### What Minecraft version is this happening on?

Minecraft 1.21.1

### What NeoForge or Fabric version is this happening on?

NeoForge 21.1.81

### What Refined Storage version is this happening on?

2.0.0-milestone.4.10

### Relevant log output

```shell
N/A
```

**Comment by raoulvdberge** [comment]
Hello there, thanks for reporting. After investigating this appears to be an issue in Silent Gear. I've reported it to them in https://github.com/SilentChaos512/Silent-Gear/issues/753

**Comment by Moj-FPS** [comment]
Thanks for the info! Appreciate you
