### ISSUE TITLE
ATM10 with RE2: Auto Crafting does not work.  Looking at Autocrafting Manager shows random Jobs showing up and going away.

### ISSUE THREAD

**Issue by ViceNoir** [refinedmods/refinedstorage2#746]
### Describe the bug

I setup an autocrafter.  Patterns are in.  When it failed I placed an Manager and I see lots of jobs showing up and going away.  I cleared all jobs and they come back and go away.  Reboot of the server does not stop this process.  Sorry I don't have an output log file. 

### How can we reproduce this bug or crash?

1. Open Autocrafter Manager and view (This will show the ghost jobs)
2. Make a pattern place it in the autocrafter. 
3. Go to crafting grid and try to auto craft.  Nothing happens.

### What Minecraft version is this happening on?

Minecraft 1.21.1

### What NeoForge or Fabric version is this happening on?

NeoForge 21.1.81

### What Refined Storage version is this happening on?

2.0.0 Milestone 4.10 with JEI intergration - Neoforge 0.6.0

**Comment by BooBooFastCat1** [comment]
autocrafting engine has not been implemented yet

**Comment by raoulvdberge** [comment]
Those are fake dummy tasks, for testing purposes. Real autocrafting is coming soon ™

**Comment by ViceNoir** [comment]
Thank makes so much more sence.  I thought it was a ghost in the machine.  AI was comming alive.  ;-)  Please close this and sorry for bothering you.

**Comment by raoulvdberge** [comment]
No worries. You never know ;)

**Comment by Lumengrid** [comment]
Hi guys, have you got any ETA for this main functionality ? Thanks

**Comment by raoulvdberge** [comment]
No ETA
