### ISSUE TITLE
JEI Integration Not Working

### ISSUE THREAD

**Issue by rolandrao** [refinedmods/refinedstorage2#750]
### Describe the bug

When opening the crafting grid in refined storage 2, there is no option to sync the JEI search field with the refined storage crafting grid search field. Also when clicking on an item in JEI, there is no option(plus button) to move the recipe to the refined storage crafting grid.
![image](https://github.com/user-attachments/assets/024bc966-a9aa-4c26-9bcf-e7817b1d4299)
![image](https://github.com/user-attachments/assets/3bca6d8d-88f6-44b7-8601-5beabc4a626b)

### How can we reproduce this bug or crash?

1. Install ATM 10 from curse forge
2. Add the refined storage 2 jar file to the mods folder of this installation
3. Create a new world and achieve a refined storage setup with a controller that is powered, crafting grid, pattern grid and disk drive with 64k storage disk inside.
4. Add a bunch of items to your storage system
5. Attempt to use crafting grid search field and attempt to find JEI synchronization button
6. Attempt to open a JEI recipe and fill the refined storage crafting grid with the recipe from JEI

### What Minecraft version is this happening on?

Minecraft 1.21.1

### What NeoForge or Fabric version is this happening on?

Neoforge 2.1

### What Refined Storage version is this happening on?

2.0.0-milestone.4.10

**Comment by Nodrance** [comment]
You need the jei addon lol

**Comment by raoulvdberge** [comment]
https://github.com/refinedmods/refinedstorage-jei-integration
