### ISSUE TITLE
Crafting grid does not move items from recipe

### ISSUE THREAD

**Issue by ThatKidSean** [refinedmods/refinedstorage2#752]
### Describe the bug

When previewing a recipe, there is usually a button next to the produced item that says "move items", which moves the recipe into the crafting table. The crafting grid does not have this option so you have to manually take the necessary items out of the storage and follow the recipe or use another source of crafting to move items from recipe. First image is the crafting table option, second image is the crafting grid option.

![image](https://github.com/user-attachments/assets/8bd49b05-d51a-4ca2-a25a-82e149ea497d)
![image](https://github.com/user-attachments/assets/66af5a7e-714c-4e7b-9b92-c87fc53ef33c)

### How can we reproduce this bug or crash?

1. Open a crafting table 
2. With the JEI menu opened on the side, left click on an item to view its recipe, there should be an option to "move items" into the crafting table.
3. Exit out
4. Open the crafting grid
5. With the JEI menu opened on the side, left click on an item to view its recipe, there is now only an option to "bookmark this recipe"

### What Minecraft version is this happening on?

Minecraft 1.21.1

### What NeoForge or Fabric version is this happening on?

Neoforge - 21.1.89

### What Refined Storage version is this happening on?

Refined Storage 2.0.0 milestone 4.11

**Comment by Nodrance** [comment]
You need the jei integration

**Comment by ThatKidSean** [comment]
Thank you, was unaware there was an additional add on needed.
