### ISSUE TITLE
Can't remove XP Drain Singularity Tank from Refined Storage

### ISSUE THREAD

**Issue by ThatKidSean** [refinedmods/refinedstorage2#754]
### Describe the bug

The XP drain singularity tank from the Mob Grinding Utils mod cannot be taken out of the refined storage when it contains liquid (storing xp). When the tank is empty, it can be taken out like any other item, but when storing xp, clicking on the item won't do anything and thus can't be taken out of the storage. Also something else I noticed is that when the controller is losing energy and goes off, access to all your items is turned off like it should be, but the xp drain singularity tank appears as being accessible but still cant be taken out, so clearly something is going wrong with that specific item. I am unable to reproduce this second bug though.

This image shows that I can pick up the tank when there is no xp fluid inside of it.
![image](https://github.com/user-attachments/assets/e2c91286-7d64-453a-8645-6aa05c800f2a)

This image shows that there is xp fluid inside and I am unable to pick it up
![image](https://github.com/user-attachments/assets/258fdfc3-5d92-4838-842d-2fc7fdecf249)

### How can we reproduce this bug or crash?

1. Create a refined storage unit with a storage part so that items can be stored in it
2. Craft a xp drain singularity tank from Mob Grinding Utils
3. Have some amount of xp levels, just say 5, and stand over the drain so that it extracts the levels
4. Break the drain and put it into the refined storage
5. Search for the drain and attempt to take it out of the storage, no inputs will allow you to take out the item

### What Minecraft version is this happening on?

Minecraft 1.21.1

### What NeoForge or Fabric version is this happening on?

NeoForge 21.1.89

### What Refined Storage version is this happening on?

v2.0.0-milestone.4.11

**Comment by Nodrance** [comment]
Looks related to https://github.com/refinedmods/refinedstorage2/issues/735 possibly?
Definitely needs to be investigated i think

**Comment by raoulvdberge** [comment]
Reported to Mob Grinding Utils here: https://github.com/vadis365/Mob-Grinding-Utils/issues/311

**Comment by raoulvdberge** [comment]
Should be fixed in this build of Mob Grinding Utils:
https://www.curseforge.com/minecraft/mc-mods/mob-grinding-utils/files/6022733
